# Generated by Django 3.2.25 on 2024-11-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
