# Generated by Django 3.2.25 on 2024-10-11 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['made_available']},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='made_avaliable',
            new_name='made_available',
        ),
    ]
