# Generated by Django 3.2.25 on 2024-10-28 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('depaul_market', '0002_auto_20241027_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='archiveProducts',
            new_name='saveProducts',
        ),
    ]
