# Generated by Django 3.2.25 on 2024-11-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0004_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('textbooks', 'Textbooks & Study Materials'), ('clothing', 'Clothing & Accessories'), ('sports', 'Sports & Outdoor Equipment'), ('music', 'Music Instruments & Equipment'), ('appliances', 'Appliances'), ('home_kitchen', 'Home & Kitchen'), ('games', 'Games'), ('events', 'Events & Tickets'), ('miscellaneous', 'Miscellaneous')], max_length=20),
        ),
    ]
