# Generated by Django 3.2.25 on 2024-11-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0005_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='campus',
            field=models.CharField(choices=[('loop', 'Loop'), ('business', 'College of Business'), ('law', 'College of Law'), ('professional_studies', 'School of Continuing and Professional Studies'), ('communication', 'College of Communication'), ('cdm', 'College of Computing and Digital Media'), ('lincoln_park', 'Lincoln Park'), ('education', 'College of Education'), ('arts_social', 'College of Liberal Arts and Social Sciences'), ('science_health', 'College of Science and Health'), ('music', 'School of Music'), ('theatre', 'Theatre School')], max_length=50),
        ),
    ]
