# Generated by Django 3.2.25 on 2024-10-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0006_usercart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercart',
            old_name='Products',
            new_name='products',
        ),
    ]
