# Generated by Django 3.2.25 on 2024-10-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0007_rename_products_usercart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='made_available',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
