# Generated by Django 3.2.25 on 2024-11-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0006_userreviews'),
        ('depaul_market', '0007_auto_20241103_0047'),
    ]

    operations = [
    ]
