# Generated by Django 3.2.25 on 2024-10-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0008_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
