# Generated by Django 3.2.25 on 2024-11-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0008_auto_20241103_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_name',
            new_name='name',
        ),
    ]
