# Generated by Django 3.2.25 on 2024-11-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0008_merge_0006_userreviews_0007_auto_20241103_0047'),
        ('depaul_market', '0009_rename_class_name_class_name'),
    ]

    operations = [
    ]
