# Generated by Django 3.2.25 on 2024-10-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0009_alter_products_made_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
