# Generated by Django 3.2.25 on 2024-11-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0010_merge_20241103_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
