# Generated by Django 3.2.25 on 2024-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0011_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='associated_classes',
            field=models.ManyToManyField(to='depaul_market.Class'),
        ),
    ]
