# Generated by Django 3.2.25 on 2024-10-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0012_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
