# Generated by Django 3.2.25 on 2024-10-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depaul_market', '0010_products_on_hold'),
        ('depaul_market', '0013_products_is_sold'),
    ]

    operations = [
    ]
